{'a', 'epsilon', '(', ')', '*', '+';'a', 'S', 'epsilon', '(', ')', '*', '+';z0, z1, z2, z3; z0; 'S'}

'z1', 'epsilon', 'S' --> 'z0', '(', 'S'
'z0', 'epsilon', 'S' --> 'z1', 'S', ')'
'z2', 'epsilon', '*' --> 'z0', 'S', '*'
'z0', 'epsilon', 'S' --> 'z2', '*', 'S'
'z3', 'epsilon', '+' --> 'z0', 'S', '+'
'z0', 'epsilon', 'S' --> 'z3', '+', 'S'
'z0', 'epsilon', 'S' --> 'z0', 'a'
'z0', 'a', 'a' --> 'z0', 'epsilon'
'z0', '(', '(' --> 'z0', 'epsilon'
'z0', ')', ')' --> 'z0', 'epsilon'
'z0', '*', '*' --> 'z0', 'epsilon'
'z0', '+', '+' --> 'z0', 'epsilon'
