/* This file was generated by SableCC (http://www.sablecc.org/). */

package GrammarParser.node;

import GrammarParser.analysis.*;

 
public final class TSymbol extends Token
{
    public TSymbol(String text)
    {
        setText(text);
    }

    public TSymbol(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSymbol(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSymbol(this);
    }
}
