/* This file was generated by SableCC (http://www.sablecc.org/). */

package AutomatonParser.analysis;

import AutomatonParser.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseARoot(ARoot node);
    void caseAStates(AStates node);
    void caseARule(ARule node);
    void caseAArgList(AArgList node);

    void caseTWhitespace(TWhitespace node);
    void caseTArrowStart(TArrowStart node);
    void caseTArrowEnd(TArrowEnd node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTLBracket2(TLBracket2 node);
    void caseTRBracket2(TRBracket2 node);
    void caseTSemicolon(TSemicolon node);
    void caseTComma(TComma node);
    void caseTIdentifier(TIdentifier node);
    void caseTListArg(TListArg node);
    void caseEOF(EOF node);
}
