/* This file was generated by SableCC (http://www.sablecc.org/). */

package AutomatonParser.analysis;

import java.util.*;
import AutomatonParser.node.*;


public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    final List<Void> dummy = new ArrayList<Void>();

    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(  Node node)
    {
        // Do nothing
    }

    public void defaultOut(  Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPRoot().apply(this);
        outStart(node);
    }

    public void inARoot(ARoot node)
    {
        defaultIn(node);
    }

    public void outARoot(ARoot node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARoot(ARoot node)
    {
        inARoot(node);
        {
            List<PRule> copy = new ArrayList<PRule>(node.getRule());
            Collections.reverse(copy);
            for(PRule e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getStates() != null)
        {
            node.getStates().apply(this);
        }
        outARoot(node);
    }

    public void inAStates(AStates node)
    {
        defaultIn(node);
    }

    public void outAStates(AStates node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStates(AStates node)
    {
        inAStates(node);
        {
            List<TIdentifier> copy = new ArrayList<TIdentifier>(node.getEndStates());
            Collections.reverse(copy);
            for(TIdentifier e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getStartState() != null)
        {
            node.getStartState().apply(this);
        }
        {
            List<TIdentifier> copy = new ArrayList<TIdentifier>(node.getAllStates());
            Collections.reverse(copy);
            for(TIdentifier e : copy)
            {
                e.apply(this);
            }
        }
        outAStates(node);
    }

    public void inARule(ARule node)
    {
        defaultIn(node);
    }

    public void outARule(ARule node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARule(ARule node)
    {
        inARule(node);
        if(node.getGoingTo() != null)
        {
            node.getGoingTo().apply(this);
        }
        {
            List<TListArg> copy = new ArrayList<TListArg>(node.getListArg());
            Collections.reverse(copy);
            for(TListArg e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getComingFrom() != null)
        {
            node.getComingFrom().apply(this);
        }
        outARule(node);
    }

    public void inAArgList(AArgList node)
    {
        defaultIn(node);
    }

    public void outAArgList(AArgList node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArgList(AArgList node)
    {
        inAArgList(node);
        {
            List<TListArg> copy = new ArrayList<TListArg>(node.getListArg());
            Collections.reverse(copy);
            for(TListArg e : copy)
            {
                e.apply(this);
            }
        }
        outAArgList(node);
    }
}
