/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser;

import node.*;
import analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTArrow(  TArrow node)
    {
        this.index = 0;
    }

    @Override
    public void caseTLBracket(  TLBracket node)
    {
        this.index = 1;
    }

    @Override
    public void caseTRBracket(  TRBracket node)
    {
        this.index = 2;
    }

    @Override
    public void caseTLBracket2(  TLBracket2 node)
    {
        this.index = 3;
    }

    @Override
    public void caseTRBracket2(  TRBracket2 node)
    {
        this.index = 4;
    }

    @Override
    public void caseTSemicolon(  TSemicolon node)
    {
        this.index = 5;
    }

    @Override
    public void caseTComma(  TComma node)
    {
        this.index = 6;
    }

    @Override
    public void caseTLine(  TLine node)
    {
        this.index = 7;
    }

    @Override
    public void caseTIdentifier(  TIdentifier node)
    {
        this.index = 8;
    }

    @Override
    public void caseTSymbol(  TSymbol node)
    {
        this.index = 9;
    }

    @Override
    public void caseEOF(  EOF node)
    {
        this.index = 10;
    }
}
