/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseARoot(ARoot node);
    void caseASymbols(ASymbols node);
    void caseARule(ARule node);

    void caseTWhitespace(TWhitespace node);
    void caseTArrow(TArrow node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTLBracket2(TLBracket2 node);
    void caseTRBracket2(TRBracket2 node);
    void caseTSemicolon(TSemicolon node);
    void caseTComma(TComma node);
    void caseTLine(TLine node);
    void caseTIdentifier(TIdentifier node);
    void caseTSymbol(TSymbol node);
    void caseEOF(EOF node);
}
