/* This file was generated by SableCC (http://www.sablecc.org/). */

package AutomatonParser.node;

import java.util.*;
import AutomatonParser.analysis.*;

 
public final class AArgList extends PArgList
{
    private final LinkedList<TListArg> _listArg_ = new LinkedList<TListArg>();

    public AArgList()
    {
        // Constructor
    }

    public AArgList(
          List<TListArg> _listArg_)
    {
        // Constructor
        setListArg(_listArg_);

    }

    @Override
    public Object clone()
    {
        return new AArgList(
            cloneList(this._listArg_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgList(this);
    }

    public LinkedList<TListArg> getListArg()
    {
        return this._listArg_;
    }

    public void setListArg(List<TListArg> list)
    {
        this._listArg_.clear();
        this._listArg_.addAll(list);
        for(TListArg e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listArg_);
    }

    @Override
    void removeChild(  Node child)
    {
        // Remove child
        if(this._listArg_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(  Node oldChild,   Node newChild)
    {
        // Replace child
        for(ListIterator<TListArg> i = this._listArg_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TListArg) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
