/* This file was generated by SableCC (http://www.sablecc.org/). */

package AutomatonParser.node;

import AutomatonParser.analysis.*;

 
public final class TArrowEnd extends Token
{
    public TArrowEnd()
    {
        super.setText("-->");
    }

    public TArrowEnd(int line, int pos)
    {
        super.setText("-->");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArrowEnd(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArrowEnd(this);
    }

    @Override
    public void setText(  String text)
    {
        throw new RuntimeException("Cannot change TArrowEnd text.");
    }
}
