/* This file was generated by SableCC (http://www.sablecc.org/). */

package AutomatonParser.node;

import AutomatonParser.analysis.*;

 
public final class TArrowStart extends Token
{
    public TArrowStart()
    {
        super.setText("--");
    }

    public TArrowStart(int line, int pos)
    {
        super.setText("--");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArrowStart(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArrowStart(this);
    }

    @Override
    public void setText(  String text)
    {
        throw new RuntimeException("Cannot change TArrowStart text.");
    }
}
