/* This file was generated by SableCC (http://www.sablecc.org/). */

package AutomatonParser.node;

import AutomatonParser.analysis.*;

 
public final class TListArg extends Token
{
    public TListArg(String text)
    {
        setText(text);
    }

    public TListArg(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TListArg(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTListArg(this);
    }
}
