package Print;

import GrammarSimulator.*;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.stream.Collectors;

import static java.util.stream.Collectors.joining;
import static java.util.stream.Collectors.toList;

/**
 * Created by Isabel on 18.11.2016.
 */
public class Printer {
    /**
     * the printEnumeration mode
     */
    public static PrintMode printmode=PrintMode.CONSOLE;
    /**
     * the current file that should be used
     */
    public static String currentFile;
    //BufferedWriter writer = new BufferedWriter(new FileWriter(fileName));

    public static int deepnes=0;
    private static BufferedWriter writer=new BufferedWriter(new OutputStreamWriter(System.out));

    public static void print(String s) {
        try {
            writer.write(s);
            writer.flush();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    public static void printEnumeration(ArrayList<Printable> printables, String[] point_descriptions, String[] texts, String titel) {
        switch(printmode) {
            case NO:
                break;
            case CONSOLE:
                printEnumerationConsole(printables,point_descriptions,texts,titel);
                break;
            case LATEX:
                printEnumerationLatex(printables,point_descriptions,texts,titel);
                break;
        }
    }

    public static void printCYKTable(Matrix matrix) {
        switch(printmode) {
            case NO:
                break;
            case LATEX:
                printCYKTableLatex(matrix);
                break;
            case CONSOLE:
                printCYKTableConsole(matrix);
                break;
        }
    }



    public static void setWriter(BufferedWriter writer) {
        Printer.writer = writer;
    }

    public static void closeWriter() {
        try {
            Printer.writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    public static boolean writerIsNull() {
        return writer==null;
    }

    /** LATEX **/
    private static void printEnumerationLatex(ArrayList<Printable> printables, String[] point_descriptions, String[] texts, String titel) {
        if(printables.size()!=texts.length) {
            return;
        }
        try {
            Printer.print("\\section{"+titel+"}\n\n");
            Printer.print("\\begin{description}\n");
            Printer.deepnes++;
            for(int i=0;i<printables.size();i++) {
                writeItem(point_descriptions[i],texts[i]);
                printables.get(i).print();

            }
            Printer.deepnes--;
            Printer.print("\\end{description}\n\n");

        } catch (IOException e) {
            e.printStackTrace();
        }

    }
    public static void printStartOfLatex() {
        Printer.print("%%this document was generated by the STUPS Toolbox 2.0\n");
        Printer.print("\\documentclass{article}\n\\" +
                "usepackage{amssymb}\n\\" +
                "usepackage{amsmath,amsthm}\n\\" +
                "usepackage[ngerman,english]{babel}\n\n\\" +
                "begin{document}\n\n");
    }
    public static void printEndOfLatex() {
        if(printmode==PrintMode.LATEX) {
            print("\\end{document}");
            try {
                writer.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
    public static String makeToGreek(String string) {
        if(string.equals("epsilon")||string.equals("lambda")) {
            return "\\"+string;
        } else {
            return string;
        }
    }


    private static void writeItem(String titel, String subtitel) throws IOException {
        String s="";
        for(int i=0;i<Printer.deepnes;i++) {
            s+="\t";
        }
        if(subtitel.isEmpty()) {
            Printer.print(s+"\\item["+titel+"] \\hfill \\\\ \n"+s+subtitel);
        } else {
            Printer.print(s+"\\item["+titel+"] \\hfill \\\\ \n"+s+subtitel+"\\\\ \n");
        }

    }

    private static void printCYKTableLatex(Matrix matrix) {
        Printer.print("\\begin{table}[h!]\n");
        Printer.print("\t\\centering\n");
        Printer.print("\t\\caption{CYK}\n");
        String s="|";
        for(int i = 0; i<matrix.getNumberOfColumns()-1; i++) {
            s+="c|";
        }
        Printer.print("\t\\begin{tabular}{"+s+"}\n");
        //1 & 2 & 3\\
        //\hline
        Printer.print("\t\t\\hline\n");
        for(int r=matrix.getNumberOfRows()-1;r>=0;r--) {
            Printer.print("\t\t");
            for(int c=1;c<matrix.getNumberOfColumns();c++) {
                Printer.print(matrix.getCell(c,r).stream().map(nonterminal -> "$"+nonterminal.getName()+"$").collect(joining(", ")));
                if(c<matrix.getNumberOfColumns()-1) {
                    Printer.print(" & ");
                }
            }


            Printer.print("\\\\\n\t\t\\hline\n");
        }
        Printer.print("\t\\end{tabular}\n");
        Printer.print("\\end{table}\n\n");

    }

    /** CONSOLE **/


    private static void printEnumerationConsole(ArrayList<Printable> printables, String[] point_description, String[] texts, String titel) {
        if(printables.size()!=texts.length) {
            return;
        }

        for(int i=0;i<printables.size();i++) {
            Printer.print(point_description[i]+": "+texts[i]+"\n");

            printables.get(i).print();

        }

    }

    private static void printCYKTableConsole(Matrix matrix) {

    }






}
