/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

 
public final class ARule extends PRule
{
    private TIdentifier _comingFrom_;
    private TSymbol _input_;
    private TSymbol _stack_;
    private final LinkedList<TSymbol> _goingTo_ = new LinkedList<TSymbol>();

    public ARule()
    {
        // Constructor
    }

    public ARule(
          TIdentifier _comingFrom_,
          TSymbol _input_,
          TSymbol _stack_,
          List<TSymbol> _goingTo_)
    {
        // Constructor
        setComingFrom(_comingFrom_);

        setInput(_input_);

        setStack(_stack_);

        setGoingTo(_goingTo_);

    }

    @Override
    public Object clone()
    {
        return new ARule(
            cloneNode(this._comingFrom_),
            cloneNode(this._input_),
            cloneNode(this._stack_),
            cloneList(this._goingTo_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARule(this);
    }

    public TIdentifier getComingFrom()
    {
        return this._comingFrom_;
    }

    public void setComingFrom(TIdentifier node)
    {
        if(this._comingFrom_ != null)
        {
            this._comingFrom_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comingFrom_ = node;
    }

    public TSymbol getInput()
    {
        return this._input_;
    }

    public void setInput(TSymbol node)
    {
        if(this._input_ != null)
        {
            this._input_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._input_ = node;
    }

    public TSymbol getStack()
    {
        return this._stack_;
    }

    public void setStack(TSymbol node)
    {
        if(this._stack_ != null)
        {
            this._stack_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stack_ = node;
    }

    public LinkedList<TSymbol> getGoingTo()
    {
        return this._goingTo_;
    }

    public void setGoingTo(List<TSymbol> list)
    {
        this._goingTo_.clear();
        this._goingTo_.addAll(list);
        for(TSymbol e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comingFrom_)
            + toString(this._input_)
            + toString(this._stack_)
            + toString(this._goingTo_);
    }

    @Override
    void removeChild(  Node child)
    {
        // Remove child
        if(this._comingFrom_ == child)
        {
            this._comingFrom_ = null;
            return;
        }

        if(this._input_ == child)
        {
            this._input_ = null;
            return;
        }

        if(this._stack_ == child)
        {
            this._stack_ = null;
            return;
        }

        if(this._goingTo_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(  Node oldChild,   Node newChild)
    {
        // Replace child
        if(this._comingFrom_ == oldChild)
        {
            setComingFrom((TIdentifier) newChild);
            return;
        }

        if(this._input_ == oldChild)
        {
            setInput((TSymbol) newChild);
            return;
        }

        if(this._stack_ == oldChild)
        {
            setStack((TSymbol) newChild);
            return;
        }

        for(ListIterator<TSymbol> i = this._goingTo_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TSymbol) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
