/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

 
public final class TRBracket2 extends Token
{
    public TRBracket2()
    {
        super.setText("}");
    }

    public TRBracket2(int line, int pos)
    {
        super.setText("}");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRBracket2(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRBracket2(this);
    }

    @Override
    public void setText(  String text)
    {
        throw new RuntimeException("Cannot change TRBracket2 text.");
    }
}
